(cl:in-package sl_controller-msg)
(cl:export '(HEADER-VAL
          HEADER
          Z_ERR-VAL
          Z_ERR
          P_ACTION_THRUST-VAL
          P_ACTION_THRUST
          I_ACTION_THRUST-VAL
          I_ACTION_THRUST
          D_ACTION_THRUST-VAL
          D_ACTION_THRUST
          E_CT-VAL
          E_CT
          DF_DELTA_POS_CT-VAL
          DF_DELTA_POS_CT
          E_CT_FEED-VAL
          E_CT_FEED
          DES_CROSS_RATE-VAL
          DES_CROSS_RATE
          DES_CROSS_RATE_SHAPED-VAL
          DES_CROSS_RATE_SHAPED
          DF_DELTA_VEL_CT-VAL
          DF_DELTA_VEL_CT
          DES_CROSS_RATE_FEED-VAL
          DES_CROSS_RATE_FEED
          CROSS_RATE_IS-VAL
          CROSS_RATE_IS
          CT_P_ACTION-VAL
          CT_P_ACTION
          CT_D_ACTION-VAL
          CT_D_ACTION
          E_AT-VAL
          E_AT
          DF_DELTA_POS_AT-VAL
          DF_DELTA_POS_AT
          E_AT_FEED-VAL
          E_AT_FEED
          DES_ALONG_RATE-VAL
          DES_ALONG_RATE
          DES_ALONG_RATE_SHAPED-VAL
          DES_ALONG_RATE_SHAPED
          DF_DELTA_VEL_AT-VAL
          DF_DELTA_VEL_AT
          DES_ALONG_RATE_FEED-VAL
          DES_ALONG_RATE_FEED
          ALONG_RATE_IS-VAL
          ALONG_RATE_IS
          AT_P_ACTION-VAL
          AT_P_ACTION
          AT_D_ACTION-VAL
          AT_D_ACTION
))