//#line 2 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the sl_controller package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __sl_controller__RECONFIGURECONFIG_H__
#define __sl_controller__RECONFIGURECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace sl_controller
{
  class reconfigureConfigStatics;
  
  class reconfigureConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(reconfigureConfig &config, const reconfigureConfig &max, const reconfigureConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const reconfigureConfig &config1, const reconfigureConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, reconfigureConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const reconfigureConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, reconfigureConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const reconfigureConfig &config) const = 0;
      virtual void getValue(const reconfigureConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T reconfigureConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (reconfigureConfig::* field);

      virtual void clamp(reconfigureConfig &config, const reconfigureConfig &max, const reconfigureConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const reconfigureConfig &config1, const reconfigureConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, reconfigureConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const reconfigureConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, reconfigureConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const reconfigureConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const reconfigureConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, reconfigureConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, reconfigureConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<reconfigureConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(reconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("Supply_type"==(*i)->name){Supply_type = boost::any_cast<int>(val);}
        if("Load_0_200"==(*i)->name){Load_0_200 = boost::any_cast<double>(val);}
        if("Frequency"==(*i)->name){Frequency = boost::any_cast<double>(val);}
        if("init_PID"==(*i)->name){init_PID = boost::any_cast<bool>(val);}
        if("load_param"==(*i)->name){load_param = boost::any_cast<bool>(val);}
        if("use_param"==(*i)->name){use_param = boost::any_cast<bool>(val);}
        if("thrust_K_P"==(*i)->name){thrust_K_P = boost::any_cast<double>(val);}
        if("thrust_K_I"==(*i)->name){thrust_K_I = boost::any_cast<double>(val);}
        if("thrust_K_D"==(*i)->name){thrust_K_D = boost::any_cast<double>(val);}
        if("thrust_max_P"==(*i)->name){thrust_max_P = boost::any_cast<double>(val);}
        if("thrust_max_I"==(*i)->name){thrust_max_I = boost::any_cast<double>(val);}
        if("thrust_max_D"==(*i)->name){thrust_max_D = boost::any_cast<double>(val);}
        if("thrust_max_PID"==(*i)->name){thrust_max_PID = boost::any_cast<double>(val);}
        if("cross_pos_K_P"==(*i)->name){cross_pos_K_P = boost::any_cast<double>(val);}
        if("cross_pos_max_P"==(*i)->name){cross_pos_max_P = boost::any_cast<double>(val);}
        if("cross_rate_K_P"==(*i)->name){cross_rate_K_P = boost::any_cast<double>(val);}
        if("cross_rate_K_D"==(*i)->name){cross_rate_K_D = boost::any_cast<double>(val);}
        if("cross_rate_max_P"==(*i)->name){cross_rate_max_P = boost::any_cast<double>(val);}
        if("cross_rate_max_D"==(*i)->name){cross_rate_max_D = boost::any_cast<double>(val);}
        if("cross_rate_max_PD"==(*i)->name){cross_rate_max_PD = boost::any_cast<double>(val);}
        if("along_pos_K_P"==(*i)->name){along_pos_K_P = boost::any_cast<double>(val);}
        if("along_pos_max_P"==(*i)->name){along_pos_max_P = boost::any_cast<double>(val);}
        if("along_rate_K_P"==(*i)->name){along_rate_K_P = boost::any_cast<double>(val);}
        if("along_rate_K_D"==(*i)->name){along_rate_K_D = boost::any_cast<double>(val);}
        if("along_rate_max_P"==(*i)->name){along_rate_max_P = boost::any_cast<double>(val);}
        if("along_rate_max_D"==(*i)->name){along_rate_max_D = boost::any_cast<double>(val);}
        if("along_rate_max_PD"==(*i)->name){along_rate_max_PD = boost::any_cast<double>(val);}
        if("N_Delay"==(*i)->name){N_Delay = boost::any_cast<int>(val);}
        if("G_d"==(*i)->name){G_d = boost::any_cast<double>(val);}
        if("l_L"==(*i)->name){l_L = boost::any_cast<double>(val);}
        if("df_sign_ct"==(*i)->name){df_sign_ct = boost::any_cast<double>(val);}
        if("df_sign_at"==(*i)->name){df_sign_at = boost::any_cast<double>(val);}
        if("is_on"==(*i)->name){is_on = boost::any_cast<int>(val);}
        if("is_N_impulses"==(*i)->name){is_N_impulses = boost::any_cast<int>(val);}
        if("is_omega_ct"==(*i)->name){is_omega_ct = boost::any_cast<double>(val);}
        if("is_omega_at"==(*i)->name){is_omega_at = boost::any_cast<double>(val);}
        if("is_zeta_ct"==(*i)->name){is_zeta_ct = boost::any_cast<double>(val);}
        if("is_zeta_at"==(*i)->name){is_zeta_at = boost::any_cast<double>(val);}
        if("test1"==(*i)->name){test1 = boost::any_cast<double>(val);}
        if("test2"==(*i)->name){test2 = boost::any_cast<double>(val);}
        if("test3"==(*i)->name){test3 = boost::any_cast<double>(val);}
        if("init_coordinate"==(*i)->name){init_coordinate = boost::any_cast<bool>(val);}
      }
    }

    int Supply_type;
double Load_0_200;
double Frequency;
bool init_PID;
bool load_param;
bool use_param;
double thrust_K_P;
double thrust_K_I;
double thrust_K_D;
double thrust_max_P;
double thrust_max_I;
double thrust_max_D;
double thrust_max_PID;
double cross_pos_K_P;
double cross_pos_max_P;
double cross_rate_K_P;
double cross_rate_K_D;
double cross_rate_max_P;
double cross_rate_max_D;
double cross_rate_max_PD;
double along_pos_K_P;
double along_pos_max_P;
double along_rate_K_P;
double along_rate_K_D;
double along_rate_max_P;
double along_rate_max_D;
double along_rate_max_PD;
int N_Delay;
double G_d;
double l_L;
double df_sign_ct;
double df_sign_at;
int is_on;
int is_N_impulses;
double is_omega_ct;
double is_omega_at;
double is_zeta_ct;
double is_zeta_at;
double test1;
double test2;
double test3;
bool init_coordinate;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int Supply_type;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double Load_0_200;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double Frequency;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool init_PID;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool load_param;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool use_param;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double thrust_K_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double thrust_K_I;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double thrust_K_D;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double thrust_max_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double thrust_max_I;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double thrust_max_D;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double thrust_max_PID;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double cross_pos_K_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double cross_pos_max_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double cross_rate_K_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double cross_rate_K_D;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double cross_rate_max_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double cross_rate_max_D;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double cross_rate_max_PD;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double along_pos_K_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double along_pos_max_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double along_rate_K_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double along_rate_K_D;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double along_rate_max_P;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double along_rate_max_D;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double along_rate_max_PD;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int N_Delay;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double G_d;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double l_L;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double df_sign_ct;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double df_sign_at;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int is_on;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int is_N_impulses;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double is_omega_ct;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double is_omega_at;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double is_zeta_ct;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double is_zeta_at;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double test1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double test2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double test3;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool init_coordinate;
//#line 255 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("reconfigureConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const reconfigureConfig &__max__ = __getMax__();
      const reconfigureConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const reconfigureConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const reconfigureConfig &__getDefault__();
    static const reconfigureConfig &__getMax__();
    static const reconfigureConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const reconfigureConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void reconfigureConfig::ParamDescription<std::string>::clamp(reconfigureConfig &config, const reconfigureConfig &max, const reconfigureConfig &min) const
  {
    return;
  }

  class reconfigureConfigStatics
  {
    friend class reconfigureConfig;
    
    reconfigureConfigStatics()
    {
reconfigureConfig::GroupDescription<reconfigureConfig::DEFAULT, reconfigureConfig> Default("Default", "", 0, 0, true, &reconfigureConfig::groups);
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Supply_type = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Supply_type = 2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Supply_type = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("Supply_type", "int", 2, "What kind of supply power will be used", "{'enum_description': 'Supply type', 'enum': [{'srcline': 16, 'description': 'Supply: Wire', 'srcfile': '../cfg/reconfigure.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Wire'}, {'srcline': 17, 'description': 'Supply: battery 2200 mAh', 'srcfile': '../cfg/reconfigure.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Battery_2200_mAh'}, {'srcline': 18, 'description': 'Supply: battery 2700 mAh', 'srcfile': '../cfg/reconfigure.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Battery_2700_mAh'}]}", &reconfigureConfig::Supply_type)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("Supply_type", "int", 2, "What kind of supply power will be used", "{'enum_description': 'Supply type', 'enum': [{'srcline': 16, 'description': 'Supply: Wire', 'srcfile': '../cfg/reconfigure.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Wire'}, {'srcline': 17, 'description': 'Supply: battery 2200 mAh', 'srcfile': '../cfg/reconfigure.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Battery_2200_mAh'}, {'srcline': 18, 'description': 'Supply: battery 2700 mAh', 'srcfile': '../cfg/reconfigure.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Battery_2700_mAh'}]}", &reconfigureConfig::Supply_type)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Load_0_200 = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Load_0_200 = 2000.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Load_0_200 = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("Load_0_200", "double", 2, "Load hanging at the copter", "", &reconfigureConfig::Load_0_200)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("Load_0_200", "double", 2, "Load hanging at the copter", "", &reconfigureConfig::Load_0_200)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Frequency = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Frequency = 50.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Frequency = 30.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("Frequency", "double", 2, "frequency of the HLC", "", &reconfigureConfig::Frequency)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("Frequency", "double", 2, "frequency of the HLC", "", &reconfigureConfig::Frequency)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.init_PID = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.init_PID = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.init_PID = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("init_PID", "bool", 1, "set the initial parameter (from file controller_patameter.yaml)", "", &reconfigureConfig::init_PID)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("init_PID", "bool", 1, "set the initial parameter (from file controller_patameter.yaml)", "", &reconfigureConfig::init_PID)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.load_param = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.load_param = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.load_param = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("load_param", "bool", 1, "load parameter from a file or record the courrent", "", &reconfigureConfig::load_param)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("load_param", "bool", 1, "load parameter from a file or record the courrent", "", &reconfigureConfig::load_param)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.use_param = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.use_param = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.use_param = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("use_param", "bool", 1, "use the loaded or saved parameter", "", &reconfigureConfig::use_param)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("use_param", "bool", 1, "use the loaded or saved parameter", "", &reconfigureConfig::use_param)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.thrust_K_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.thrust_K_P = 300.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.thrust_K_P = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_K_P", "double", 2, "K_P z PID controller", "", &reconfigureConfig::thrust_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_K_P", "double", 2, "K_P z PID controller", "", &reconfigureConfig::thrust_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.thrust_K_I = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.thrust_K_I = 30.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.thrust_K_I = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_K_I", "double", 2, "K_I z PID controller", "", &reconfigureConfig::thrust_K_I)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_K_I", "double", 2, "K_I z PID controller", "", &reconfigureConfig::thrust_K_I)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.thrust_K_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.thrust_K_D = 150.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.thrust_K_D = 50.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_K_D", "double", 2, "K_D z PID controller", "", &reconfigureConfig::thrust_K_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_K_D", "double", 2, "K_D z PID controller", "", &reconfigureConfig::thrust_K_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.thrust_max_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.thrust_max_P = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.thrust_max_P = 30.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_P", "double", 2, "P_action max z PID controller", "", &reconfigureConfig::thrust_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_P", "double", 2, "P_action max z PID controller", "", &reconfigureConfig::thrust_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.thrust_max_I = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.thrust_max_I = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.thrust_max_I = 30.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_I", "double", 2, "I_action max z PID controlle", "", &reconfigureConfig::thrust_max_I)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_I", "double", 2, "I_action max z PID controlle", "", &reconfigureConfig::thrust_max_I)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.thrust_max_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.thrust_max_D = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.thrust_max_D = 40.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_D", "double", 2, "D_action max z PID controlle", "", &reconfigureConfig::thrust_max_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_D", "double", 2, "D_action max z PID controlle", "", &reconfigureConfig::thrust_max_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.thrust_max_PID = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.thrust_max_PID = 500.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.thrust_max_PID = 200.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_PID", "double", 2, "PID_action max z PID controlle", "", &reconfigureConfig::thrust_max_PID)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("thrust_max_PID", "double", 2, "PID_action max z PID controlle", "", &reconfigureConfig::thrust_max_PID)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cross_pos_K_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cross_pos_K_P = 2.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cross_pos_K_P = 0.6;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_pos_K_P", "double", 2, "K_P cross position controller", "", &reconfigureConfig::cross_pos_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_pos_K_P", "double", 2, "K_P cross position controller", "", &reconfigureConfig::cross_pos_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cross_pos_max_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cross_pos_max_P = 3.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cross_pos_max_P = 0.8;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_pos_max_P", "double", 2, "P_action max corss position controller", "", &reconfigureConfig::cross_pos_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_pos_max_P", "double", 2, "P_action max corss position controller", "", &reconfigureConfig::cross_pos_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cross_rate_K_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cross_rate_K_P = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cross_rate_K_P = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_K_P", "double", 2, "K_P cross rate controller", "", &reconfigureConfig::cross_rate_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_K_P", "double", 2, "K_P cross rate controller", "", &reconfigureConfig::cross_rate_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cross_rate_K_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cross_rate_K_D = 0.1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cross_rate_K_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_K_D", "double", 2, "K_D cross rate controller", "", &reconfigureConfig::cross_rate_K_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_K_D", "double", 2, "K_D cross rate controller", "", &reconfigureConfig::cross_rate_K_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cross_rate_max_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cross_rate_max_P = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cross_rate_max_P = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_max_P", "double", 2, "P_action max cross rate controller", "", &reconfigureConfig::cross_rate_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_max_P", "double", 2, "P_action max cross rate controller", "", &reconfigureConfig::cross_rate_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cross_rate_max_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cross_rate_max_D = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cross_rate_max_D = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_max_D", "double", 2, "D_action max cross rate controller", "", &reconfigureConfig::cross_rate_max_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_max_D", "double", 2, "D_action max cross rate controller", "", &reconfigureConfig::cross_rate_max_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.cross_rate_max_PD = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.cross_rate_max_PD = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.cross_rate_max_PD = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_max_PD", "double", 2, "PD_action max cross rate controller", "", &reconfigureConfig::cross_rate_max_PD)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("cross_rate_max_PD", "double", 2, "PD_action max cross rate controller", "", &reconfigureConfig::cross_rate_max_PD)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.along_pos_K_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.along_pos_K_P = 2.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.along_pos_K_P = 0.6;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_pos_K_P", "double", 2, "K_P along position controller", "", &reconfigureConfig::along_pos_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_pos_K_P", "double", 2, "K_P along position controller", "", &reconfigureConfig::along_pos_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.along_pos_max_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.along_pos_max_P = 3.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.along_pos_max_P = 0.8;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_pos_max_P", "double", 2, "P_action max along position controller", "", &reconfigureConfig::along_pos_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_pos_max_P", "double", 2, "P_action max along position controller", "", &reconfigureConfig::along_pos_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.along_rate_K_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.along_rate_K_P = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.along_rate_K_P = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_K_P", "double", 2, "K_P along rate controller", "", &reconfigureConfig::along_rate_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_K_P", "double", 2, "K_P along rate controller", "", &reconfigureConfig::along_rate_K_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.along_rate_K_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.along_rate_K_D = 0.1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.along_rate_K_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_K_D", "double", 2, "K_D along rate controller", "", &reconfigureConfig::along_rate_K_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_K_D", "double", 2, "K_D along rate controller", "", &reconfigureConfig::along_rate_K_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.along_rate_max_P = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.along_rate_max_P = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.along_rate_max_P = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_max_P", "double", 2, "P_action max along rate controller", "", &reconfigureConfig::along_rate_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_max_P", "double", 2, "P_action max along rate controller", "", &reconfigureConfig::along_rate_max_P)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.along_rate_max_D = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.along_rate_max_D = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.along_rate_max_D = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_max_D", "double", 2, "D_action max along rate controller", "", &reconfigureConfig::along_rate_max_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_max_D", "double", 2, "D_action max along rate controller", "", &reconfigureConfig::along_rate_max_D)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.along_rate_max_PD = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.along_rate_max_PD = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.along_rate_max_PD = 0.2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_max_PD", "double", 2, "PD_action max along rate controller", "", &reconfigureConfig::along_rate_max_PD)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("along_rate_max_PD", "double", 2, "PD_action max along rate controller", "", &reconfigureConfig::along_rate_max_PD)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.N_Delay = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.N_Delay = 20;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.N_Delay = 3;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("N_Delay", "int", 2, "Numbers of loops to wait untill feeding the angles", "", &reconfigureConfig::N_Delay)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("N_Delay", "int", 2, "Numbers of loops to wait untill feeding the angles", "", &reconfigureConfig::N_Delay)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.G_d = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.G_d = 0.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.G_d = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("G_d", "double", 2, "Gain on the load angles", "", &reconfigureConfig::G_d)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("G_d", "double", 2, "Gain on the load angles", "", &reconfigureConfig::G_d)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.l_L = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.l_L = 2.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.l_L = 0.6;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("l_L", "double", 2, "length from the copter CoG to puppet CoG", "", &reconfigureConfig::l_L)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("l_L", "double", 2, "length from the copter CoG to puppet CoG", "", &reconfigureConfig::l_L)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.df_sign_ct = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.df_sign_ct = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.df_sign_ct = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("df_sign_ct", "double", 2, "Sign for delay cross track", "", &reconfigureConfig::df_sign_ct)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("df_sign_ct", "double", 2, "Sign for delay cross track", "", &reconfigureConfig::df_sign_ct)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.df_sign_at = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.df_sign_at = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.df_sign_at = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("df_sign_at", "double", 2, "Sign for delay along track", "", &reconfigureConfig::df_sign_at)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("df_sign_at", "double", 2, "Sign for delay along track", "", &reconfigureConfig::df_sign_at)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.is_on = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.is_on = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.is_on = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("is_on", "int", 2, "turn input shaper on and off", "", &reconfigureConfig::is_on)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("is_on", "int", 2, "turn input shaper on and off", "", &reconfigureConfig::is_on)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.is_N_impulses = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.is_N_impulses = 5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.is_N_impulses = 2;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("is_N_impulses", "int", 2, "Number of impulses", "", &reconfigureConfig::is_N_impulses)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<int>("is_N_impulses", "int", 2, "Number of impulses", "", &reconfigureConfig::is_N_impulses)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.is_omega_ct = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.is_omega_ct = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.is_omega_ct = 0.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_omega_ct", "double", 2, "Frequency cross track", "", &reconfigureConfig::is_omega_ct)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_omega_ct", "double", 2, "Frequency cross track", "", &reconfigureConfig::is_omega_ct)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.is_omega_at = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.is_omega_at = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.is_omega_at = 0.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_omega_at", "double", 2, "Frequency along track", "", &reconfigureConfig::is_omega_at)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_omega_at", "double", 2, "Frequency along track", "", &reconfigureConfig::is_omega_at)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.is_zeta_ct = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.is_zeta_ct = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.is_zeta_ct = 0.1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_zeta_ct", "double", 2, "damping cross track", "", &reconfigureConfig::is_zeta_ct)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_zeta_ct", "double", 2, "damping cross track", "", &reconfigureConfig::is_zeta_ct)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.is_zeta_at = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.is_zeta_at = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.is_zeta_at = 0.1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_zeta_at", "double", 2, "damping along track", "", &reconfigureConfig::is_zeta_at)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("is_zeta_at", "double", 2, "damping along track", "", &reconfigureConfig::is_zeta_at)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.test1 = -100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.test1 = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.test1 = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("test1", "double", 2, "debug channel 1", "", &reconfigureConfig::test1)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("test1", "double", 2, "debug channel 1", "", &reconfigureConfig::test1)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.test2 = -100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.test2 = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.test2 = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("test2", "double", 2, "debug channel 2", "", &reconfigureConfig::test2)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("test2", "double", 2, "debug channel 2", "", &reconfigureConfig::test2)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.test3 = -100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.test3 = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.test3 = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("test3", "double", 2, "debug channel 3", "", &reconfigureConfig::test3)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<double>("test3", "double", 2, "debug channel 3", "", &reconfigureConfig::test3)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.init_coordinate = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.init_coordinate = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.init_coordinate = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("init_coordinate", "bool", 1, "initialize the coordinate system where the copter in this moment is", "", &reconfigureConfig::init_coordinate)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(reconfigureConfig::AbstractParamDescriptionConstPtr(new reconfigureConfig::ParamDescription<bool>("init_coordinate", "bool", 1, "initialize the coordinate system where the copter in this moment is", "", &reconfigureConfig::init_coordinate)));
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(reconfigureConfig::AbstractGroupDescriptionConstPtr(new reconfigureConfig::GroupDescription<reconfigureConfig::DEFAULT, reconfigureConfig>(Default)));
//#line 390 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<reconfigureConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<reconfigureConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<reconfigureConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    reconfigureConfig __max__;
    reconfigureConfig __min__;
    reconfigureConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const reconfigureConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static reconfigureConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &reconfigureConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const reconfigureConfig &reconfigureConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const reconfigureConfig &reconfigureConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const reconfigureConfig &reconfigureConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<reconfigureConfig::AbstractParamDescriptionConstPtr> &reconfigureConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<reconfigureConfig::AbstractGroupDescriptionConstPtr> &reconfigureConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const reconfigureConfigStatics *reconfigureConfig::__get_statics__()
  {
    const static reconfigureConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = reconfigureConfigStatics::get_instance();
    
    return statics;
  }

//#line 11 "../cfg/reconfigure.cfg"
      const int reconfigure_INIT_FILTER = 1;
//#line 12 "../cfg/reconfigure.cfg"
      const int reconfigure_MISC = 2;
//#line 16 "../cfg/reconfigure.cfg"
      const int reconfigure_Wire = 0;
//#line 17 "../cfg/reconfigure.cfg"
      const int reconfigure_Battery_2200_mAh = 1;
//#line 18 "../cfg/reconfigure.cfg"
      const int reconfigure_Battery_2700_mAh = 2;
}

#endif // __RECONFIGURERECONFIGURATOR_H__
