/* Auto-generated by genmsg_cpp for file /home/mafilipp/fuerte_workspace/sandbox/sl_controller/msg/waypoint.msg */
#ifndef SL_CONTROLLER_MESSAGE_WAYPOINT_H
#define SL_CONTROLLER_MESSAGE_WAYPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace sl_controller
{
template <class ContainerAllocator>
struct waypoint_ {
  typedef waypoint_<ContainerAllocator> Type;

  waypoint_()
  : header()
  , x_ref(0.0)
  , y_ref(0.0)
  , z_ref(0.0)
  , dz_ref(0.0)
  , v_ref(0.0)
  , number_path(0.0)
  {
  }

  waypoint_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x_ref(0.0)
  , y_ref(0.0)
  , z_ref(0.0)
  , dz_ref(0.0)
  , v_ref(0.0)
  , number_path(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _x_ref_type;
  double x_ref;

  typedef double _y_ref_type;
  double y_ref;

  typedef double _z_ref_type;
  double z_ref;

  typedef double _dz_ref_type;
  double dz_ref;

  typedef double _v_ref_type;
  double v_ref;

  typedef double _number_path_type;
  double number_path;


  typedef boost::shared_ptr< ::sl_controller::waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sl_controller::waypoint_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct waypoint
typedef  ::sl_controller::waypoint_<std::allocator<void> > waypoint;

typedef boost::shared_ptr< ::sl_controller::waypoint> waypointPtr;
typedef boost::shared_ptr< ::sl_controller::waypoint const> waypointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sl_controller::waypoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sl_controller::waypoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sl_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sl_controller::waypoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sl_controller::waypoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sl_controller::waypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "31ecdefa009964edb4b11780ca66870c";
  }

  static const char* value(const  ::sl_controller::waypoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x31ecdefa009964edULL;
  static const uint64_t static_value2 = 0xb4b11780ca66870cULL;
};

template<class ContainerAllocator>
struct DataType< ::sl_controller::waypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sl_controller/waypoint";
  }

  static const char* value(const  ::sl_controller::waypoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sl_controller::waypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header    header\n\
\n\
float64 x_ref\n\
float64 y_ref\n\
float64 z_ref\n\
float64 dz_ref\n\
float64 v_ref\n\
float64 number_path\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::sl_controller::waypoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::sl_controller::waypoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::sl_controller::waypoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sl_controller::waypoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x_ref);
    stream.next(m.y_ref);
    stream.next(m.z_ref);
    stream.next(m.dz_ref);
    stream.next(m.v_ref);
    stream.next(m.number_path);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct waypoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sl_controller::waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sl_controller::waypoint_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x_ref: ";
    Printer<double>::stream(s, indent + "  ", v.x_ref);
    s << indent << "y_ref: ";
    Printer<double>::stream(s, indent + "  ", v.y_ref);
    s << indent << "z_ref: ";
    Printer<double>::stream(s, indent + "  ", v.z_ref);
    s << indent << "dz_ref: ";
    Printer<double>::stream(s, indent + "  ", v.dz_ref);
    s << indent << "v_ref: ";
    Printer<double>::stream(s, indent + "  ", v.v_ref);
    s << indent << "number_path: ";
    Printer<double>::stream(s, indent + "  ", v.number_path);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SL_CONTROLLER_MESSAGE_WAYPOINT_H

